imports:
    - path: vm-template.py
    - path: startup-script.sh
    
resources:
    - name: app-vm
      type: vm-template.py
      properties:
        zone: us-central1-f
        machine-type: g1-small
        metadata-from-file:
            startup-script: startup-script.sh
